### ISSUE TITLE
events

### ISSUE THREAD

**Issue by martinjrobins** [martinjrobins/diffsol#42]
There needs to be a way for the user to specify events at which to terminate the solve. This could be another function in the `OdeEquations` trait that writes to a vector given the current state x and time t. The solver will terminate if any of the elements in that vector cross zero

**Comment by mirams** [comment]
CVODE describes it as 'rootfinding' see the good documentation here https://sundials.readthedocs.io/en/latest/cvode/Mathematics_link.html#rootfinding 

But note that in the special case that the events are at pre-specified times, then the rootfinding is a waste of effort!

**Comment by martinjrobins** [comment]
yea, in regard to the special case that the events are at a set time: This might need its own interface, at the moment you can "step" forward the solver and it chooses its own timestep (say to t2). If you want to get the solution at an arbitrary time point before t2 (say t1) you can using the "interpolate" function, but this doesn't change the internal state of the solver (which is still at t2). 

In the case of an event at a pre-specified time, what you really want is for the internal state of the solver to stop at t1. Perhaps the "step" function can have a maximum time point input that it will stop at.

**Comment by martinjrobins** [comment]
Thanks for the link, that is very helpful!

**Comment by mirams** [comment]
> yea, in regard to the special case that the events are at a set time: This might need its own interface, at the moment you can "step" forward the solver and it chooses its own timestep (say to t2). If you want to get the solution at an arbitrary time point before t2 (say t1) you can using the "interpolate" function, but this doesn't change the internal state of the solver (which is still at t2).
> 
> In the case of an event at a pre-specified time, what you really want is for the internal state of the solver to stop at t1. Perhaps the "step" function can have a maximum time point input that it will stop at.

Yeah, all this is another thing CVODE does nicely, with a "hit the exact time I told you to stop at" option (`NORMAL_TSTOP`)
<img width="703" alt="image" src="https://github.com/martinjrobins/diffsol/assets/858776/f8a016c0-182d-48fc-8a30-d39d58e8cd8f">
from https://computing.llnl.gov/projects/sundials/usage-notes
